# Generated by Django 4.1.5 on 2023-03-02 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
        ('posts', '0004_alter_post_image_comment'),
    ]

    operations = [
    ]
