# Generated by Django 4.1.5 on 2023-03-02 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_merge_20230302_0130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
